# Huffman Coding

1 point

1.In this programming problem and the next you'll code up the greedy algorithm from the lectures on Huffman coding.

Download the text file below.

[huffman.txt](https://github.com/SSQ/Coursera-Stanford-Greedy-Algorithms-Minimum-Spanning-Trees-and-Dynamic-Programming/blob/master/Programming%20Assignment%203/huffman.txt)
This file describes an instance of the problem. It has the following format:

[number_of_symbols]

[weight of symbol #1]

[weight of symbol #2]

...

For example, the third line of the file is "6852892," indicating that the weight of the second symbol of the alphabet is 6852892. (We're using weights instead of frequencies, like in the "A More Complex Example" video.)

Your task in this problem is to run the Huffman coding algorithm from lecture on this data set. What is the maximum length of a codeword in the resulting Huffman code?

ADVICE: If you're not getting the correct answer, try debugging your algorithm using some small test cases. And then post them to the discussion forum!


<input type=”text” placeholder="Enter answer here">
<br>

In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
# get the file path
file_path = 'huffman.txt'
# file_path = 'test 1.txt'
# convert text file to np.array type
huffman_data = np.loadtxt(file_path)
int_huffman_data = huffman_data.astype(int)

# test
print('int_huffman_data[:3]: ')
print(int_huffman_data[:3])

int_huffman_data[:3]: 
[7540662 6852892 3235725]


In [3]:
# sort the weights inscreasing order
sorted_data = np.sort(int_huffman_data)
sorted_index = np.argsort(int_huffman_data) 

# test
for i in range(len(sorted_data)):
    if sorted_data[i] != [int_huffman_data[x] for x in sorted_index][i]:
        print("sorted failed")
        break
print("sorted successfully")

sorted successfully


In [4]:
# test

print(sorted_data[:10])
print(sorted_data[-10:])

sorted_data = np.append(sorted_data, sorted_data[0] + sorted_data[1])

sorted_data = np.delete(sorted_data, [0, 1])

print(sorted_data[:10])
print(sorted_data[-10:])

[ 1873 12710 37164 40882 57802 61282 64537 70116 83429 90939]
[9879636 9879739 9889780 9911792 9916957 9933557 9959436 9968891 9978358
 9979223]
[ 37164  40882  57802  61282  64537  70116  83429  90939  97421 107416]
[9879739 9889780 9911792 9916957 9933557 9959436 9968891 9978358 9979223
   14583]


In [5]:
# test 
print(sorted_index[:10])
print(sorted_index[-10:])

sorted_index = np.delete(sorted_index, [0, 1])

print(sorted_index[:10])
print(sorted_index[-10:])

[471 798 752 448 554 867 356 957 598 382]
[701 773 430 896 876 105  33 780 514 342]
[752 448 554 867 356 957 598 382 210 538]
[701 773 430 896 876 105  33 780 514 342]


In [7]:
# test

test_data={}
for i in range(len(int_huffman_data)):
    test_data[int_huffman_data[i]] = [i]
print(test_data)
print(int_huffman_data[0])
print(sorted(test_data))

{569344: [188], 2664448: [378], 5289986: [271], 7946249: [172], 5474314: [131], 9979223: [342], 9959436: [33], 1990671: [711], 7705902: [814], 5666836: [657], 6338581: [152], 3333465: [676], 1062936: [776], 8157209: [507], 3741722: [207], 9353243: [30], 3237916: [465], 5734430: [828], 3802117: [938], 4536352: [887], 9218081: [183], 6985762: [420], 8972323: [195], 9717796: [182], 4966440: [496], 7231836: [20], 1151019: [91], 5767214: [948], 1153072: [137], 1265714: [146], 2207795: [500], 149557: [174], 7409718: [506], 1771529: [958], 7045177: [390], 1385141: [782], 7807042: [494], 4849731: [45], 8808519: [309], 8001611: [845], 7116876: [191], 356432: [810], 7856211: [406], 9879636: [701], 9603157: [126], 2353241: [278], 8874074: [42], 8982619: [708], 6971484: [60], 1833054: [512], 7276642: [125], 1331899: [633], 9285990: [395], 6103143: [903], 9844247: [719], 3121259: [668], 456813: [452], 7729267: [394], 6843026: [555], 8007799: [842], 4012152: [608], 8452218: [785], 4415850: [308], 37

In [ ]:
WeightPosition={}
for i in range(len(int_huffman_data)):
    WeightPosition[int_huffman_data[i]] = [i]

def HuffmanCode(WeightPosition):
    if len(WeightPosition) == 2:
        
    else:
        sorted_data = np.sort(WeightPosition)
        sorted_index = [[x] for x in np.argsort(WeightPosition)]
        
        sorted_data = np.append(sorted_data, sorted_data[0] + sorted_data[1])
        sorted_data = np.delete(sorted_data, [0, 1])
        
        
        sorted_index = np.append(sorted_index, np.append(sorted_index[0], sorted_index[1], axis=0), axis=0)
        sorted_index = np.delete(sorted_index, [0, 1])

1 point
2.Continuing the previous problem, what is the minimum length of a codeword in your Huffman code?

<input type=”text” placeholder="Enter answer here">
<br>