# Clustering 1

1 point
1.In this programming problem and the next you'll code up the clustering algorithm from lecture for computing a max-spacing k-clustering.

Download the text file below.

[clustering1.txt](https://d3c33hcgiwev3.cloudfront.net/_fe8d0202cd20a808db6a4d5d06be62f4_clustering1.txt?Expires=1501545600&Signature=CXDeXP4OyEgCos4pTCADKwX5wOUahg23xtVefKBK88DOVRwPEDLrvtcqdZSV5vR7kZXEi4NZl-WnCSYcG8CDoCKTXu17ESQg3YwocNokp-Ghfx3cSjW59Xu7LTyEwefRMnaDa225KQEIxfCItdsUKIpdm6MdGXCI3hRsS3oHJrY_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A)

This file describes a distance function (equivalently, a complete graph with edge costs). It has the following format:

[number_of_nodes]

[edge 1 node 1] [edge 1 node 2] [edge 1 cost]

[edge 2 node 1] [edge 2 node 2] [edge 2 cost]

...

There is one edge (i,j) for each choice of 1≤i<j≤n, where n is the number of nodes.

For example, the third line of the file is "1 3 5250", indicating that the distance between nodes 1 and 3 (equivalently, the cost of the edge (1,3)) is 5250. You can assume that distances are positive, but you should NOT assume that they are distinct.

Your task in this problem is to run the clustering algorithm from lecture on this data set, where the target number k of clusters is set to 4. What is the maximum spacing of a 4-clustering?

ADVICE: If you're not getting the correct answer, try debugging your algorithm using some small test cases. And then post them to the discussion forum!


<input type=”text” placeholder="Enter answer here">

In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
# get the file path
file_path = 'clustering1.txt'
# file_path = 'test 1.txt'
# convert text file to np.array type
clustering_data = np.loadtxt(file_path)
int_clustering_data = clustering_data.astype(int)
print('int_clustering_data: ')
print(int_clustering_data)

int_clustering_data: 
[[   1    2 6808]
 [   1    3 5250]
 [   1    4   74]
 ..., 
 [ 498  499 5758]
 [ 498  500 4881]
 [ 499  500 8273]]


convert directed graph into undirected graph

data = np.copy(int_clustering_data)
data[:,[0,1]] = int_clustering_data[:,[1,0]]
print('data: ')
print(data)
print('int_clustering_data: ')
print(int_clustering_data)
undirected_graph = np.concatenate((int_clustering_data, data))
print('undirected_graph: ')
print(undirected_graph)

In [3]:
# test1 initialize a cluster
test_clusters = {}
for x in range(1,10):
    test_clusters[x] = [x]
    
print('test_clusters: ')
print(test_clusters)

test_clusters: 
{1: [1], 2: [2], 3: [3], 4: [4], 5: [5], 6: [6], 7: [7], 8: [8], 9: [9]}


In [4]:
# test2 extend and del key
test_dic = {1:[1],2:[2],3:[3,4]}
print('test_dic')
print(test_dic)

test_dic[1].extend(test_dic[3])
print('test_dic')
print(test_dic)
del test_dic[3]
print('test_dic')
print(test_dic)

test_dic
{1: [1], 2: [2], 3: [3, 4]}
test_dic
{1: [1, 3, 4], 2: [2], 3: [3, 4]}
test_dic
{1: [1, 3, 4], 2: [2]}


In [5]:
# clustering algorithm

# test1 can be found before
# Initially, each point in a separate cluster,we have 500 nodes
clusters = {}
for x in range(1,501):
    clusters[x] = [x]
print('clusters: ')
print(clusters)
# print('clusters: ')
# print(clusters)

# sort the distance of nodes
sorted_index = np.argsort(int_clustering_data[:,2], axis=0) 

# set the number of clusters 
k = 4

# def a function to get the key by value in dictionary
# d: dictionary
# k: key
def get_key_by_value(d, k):
    for leader, nodes in d.items():
        if k in nodes:
            return leader

# test2 can be found before
# c: dictionary. cluster 
# a: key. added value in dict
# d: key. deleted value in dict
def update_cluster(c, a, d):
    c[a].extend(c[d])
    del c[d]

# initialize number of iteration    
iteration = 0

# 
print('whole_edges: ')
print(len(sorted_index))

# core algorithm
start_time = time.time()
for i in sorted_index:
    # print('i: ')
    # print(i)
    
    #iteration = iteration + 1
    # print('iteration: ')
    # print(iteration)
    min_edge = int_clustering_data[i,:]
    key1 = get_key_by_value(clusters, min_edge[0])
    key2 = get_key_by_value(clusters, min_edge[1])
    if key1 == key2:
        continue
    elif len(clusters[key1]) >= len(clusters[key2]):
        update_cluster(clusters, key1, key2)
    else:
        update_cluster(clusters, key2, key1)

    # print('k: ')
    # print(len(clusters))
    if len(clusters) == k:
        break
        
end_time = time.time()
print('time: ' + str(end_time - start_time) + 's ')
print('time: ' + str((end_time - start_time) / 60) + 'min')
print('time: ' + str((end_time - start_time) / 3600) + 'h')
print('clusters: ')
print(clusters)

clusters: 
{1: [1], 2: [2], 3: [3], 4: [4], 5: [5], 6: [6], 7: [7], 8: [8], 9: [9], 10: [10], 11: [11], 12: [12], 13: [13], 14: [14], 15: [15], 16: [16], 17: [17], 18: [18], 19: [19], 20: [20], 21: [21], 22: [22], 23: [23], 24: [24], 25: [25], 26: [26], 27: [27], 28: [28], 29: [29], 30: [30], 31: [31], 32: [32], 33: [33], 34: [34], 35: [35], 36: [36], 37: [37], 38: [38], 39: [39], 40: [40], 41: [41], 42: [42], 43: [43], 44: [44], 45: [45], 46: [46], 47: [47], 48: [48], 49: [49], 50: [50], 51: [51], 52: [52], 53: [53], 54: [54], 55: [55], 56: [56], 57: [57], 58: [58], 59: [59], 60: [60], 61: [61], 62: [62], 63: [63], 64: [64], 65: [65], 66: [66], 67: [67], 68: [68], 69: [69], 70: [70], 71: [71], 72: [72], 73: [73], 74: [74], 75: [75], 76: [76], 77: [77], 78: [78], 79: [79], 80: [80], 81: [81], 82: [82], 83: [83], 84: [84], 85: [85], 86: [86], 87: [87], 88: [88], 89: [89], 90: [90], 91: [91], 92: [92], 93: [93], 94: [94], 95: [95], 96: [96], 97: [97], 98: [98], 99: [99], 100: [100], 101:

In [6]:
clusters_keys = clusters.keys() # [102, 384, 414, 462]

# initialize 
spacing = []

distance=0
# set all spacing of k-clusters
for i in range(len(clusters_keys)-1):
    j = i+1
    for k in range(j, len(clusters_keys)):
        spacing.append([clusters_keys[i], clusters_keys[k], distance])
spacing = np.array(spacing)
print('spacing: ')
print(spacing)

spacing: 
[[102 384   0]
 [102 414   0]
 [102 462   0]
 [384 414   0]
 [384 462   0]
 [414 462   0]]


In [7]:
# test
print(spacing[:,0]==102)
print(spacing[:,0])
print(spacing[:,1]==462)
print(np.all([spacing[:,0]==102, spacing[:,1]==462], axis=0))
test = np.all([spacing[:,0]==102, spacing[:,1]==462], axis=0)

print(np.argwhere(test==True)) 
print(np.argwhere(test==True)[0][0]) 

print(type(np.argwhere(test==True)))
print(spacing[np.argwhere(test==False),:])
print(len(spacing[np.argwhere(test==False),:]))
print(spacing[np.argwhere(test==False)[0][0],:])



[ True  True  True False False False]
[102 102 102 384 384 414]
[False False  True False  True  True]
[False False  True False False False]
[[2]]
2
<type 'numpy.ndarray'>
[[[102 384   0]]

 [[102 414   0]]

 [[384 414   0]]

 [[384 462   0]]

 [[414 462   0]]]
5
[102 384   0]


In [8]:
def min_distance(int_clustering_data, clusters, cluster1, cluster2):
    minimum = int_clustering_data[:,2].max()
    # print('minimum: ')
    # print(minimum)
    for i in clusters[cluster1]:
        # print('i: ')
        # print(i)
        for j in clusters[cluster2]:
            # print('j: ')
            # print(j)
            if i < j:
                find_position = np.all([int_clustering_data[:,0]==i, int_clustering_data[:,1]==j], axis=0)
                find_edge = np.argwhere(find_position==True)
                actural_position = find_edge[0][0]
                distance = int_clustering_data[actural_position, 2]
                if minimum > distance:
                    minimum = distance
            else:
                find_position = np.all([int_clustering_data[:,0]==j, int_clustering_data[:,1]==i], axis=0)
                find_edge = np.argwhere(find_position==True)
                actural_position = find_edge[0][0]
                distance = int_clustering_data[actural_position, 2]
                if minimum > distance:
                    minimum = distance
            # print('minimum: ')
            # print(minimum)
    return minimum
            

In [9]:

for i in range(len(spacing)):
    spacing[i,2] = min_distance(int_clustering_data, clusters, spacing[i,0], spacing[i,1])


In [10]:
print('spacing: ')
print(spacing)
print('max distance clusters: ')
print(spacing[np.argmax(spacing[:,2]), :])
print('max distance: ')
print(np.amax(spacing[:,2]))

spacing: 
[[ 102  384  123]
 [ 102  414  106]
 [ 102  462  107]
 [ 384  414 1162]
 [ 384  462 1641]
 [ 414  462  746]]
max distance clusters: 
[ 384  462 1641]
max distance: 
1641


# Question1 Answer

1641